### ISSUE TITLE
importlib problems

### ISSUE THREAD

**Issue by johanna27045** [VCIP-RGBD/DFormer#22]
I think your approach is very interesting and wanted to try it myself. When setting up the repository I encountered following problem:

 File "C:\Users\jk267\DFormer\utils\train.py", line 116, in <module>
    config = getattr(import_module(args.config), "C")
  File "C:\Users\jk267\.conda\envs\dformer\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jk267\DFormer\.\local_configs\NYUDepthv2\DFormer_Large.py", line 4, in <module>
    C.backbone = "DFormer-Large"  # Remember change the path below.
NameError: name 'C' is not defined

I think I may have some package problems, because of not installed packages or libs. Are the installations in readme point 0 all I need and do you have an idea what I could do? 

Thank you for your response beforehand.

**Comment by caojiaolong** [comment]
Thank you for your attention to our work!

It appears that our code behaves differently on a Windows system. Since we do not have access to a Windows machine with graphic cards, it is challenging for us to reproduce this issue. Therefore, we propose two potential solutions:

1. Change the following line:
   https://github.com/VCIP-RGBD/DFormer/blob/3dd8a45fb1e294b2c39f0664c66eaeeb385aaa47/train.sh#L10
   to 
```bash
PYTHONPATH="$(dirname $0) \"
```
 as the PYTHONPATH structure might be different on Windows.

2. If the above approach doesn't resolve the issue, there's another workaround. You can manually copy the code from `local_configs/_base_/__init__.py` and `local_configs/_base_/datasets/NYUDepthv2.py` into `local_configs/NYUDepthv2/DFormer_Large.py`. This will create a single large config file. Then, rerun the code.

If the above methods still do not solve the problem, please provide more information so we can try to address the issue.

**Comment by johanna27045** [comment]
I apologize for the late answer. 

We did change the line with 

PYTHONPATH="$(dirname $0)/..":"$(dirname $0)":$PYTHONPATH \ 

and it worked out. 
Another thing we noticed was, that there were problems when using only 1 GPU, because the local rank is not set then. 
We added 
        else:
            self.local_rank = int(os.environ['LOCAL_RANK']) 
            self.devices = [0, 1]  # parse_devices(self.args.devices)
in engine.py line 67, 67, 69 and it seems to work out this way.
